# 开发环境配置
smart-hr:
  ai:
    default-model: openai
    aliyun:
      enabled: false

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root: INFO
    com.smarthr: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

